/*
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Dbv0037Error;
import org.openapitools.client.model.Dbv0037TresListInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Dbv0037TresInfo
 */
public class Dbv0037TresInfoTest {
    private final Dbv0037TresInfo model = new Dbv0037TresInfo();

    /**
     * Model tests for Dbv0037TresInfo
     */
    @Test
    public void testDbv0037TresInfo() {
        // TODO: test Dbv0037TresInfo
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

    /**
     * Test the property 'tres'
     */
    @Test
    public void tresTest() {
        // TODO: test tres
    }

}
