/*
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Dbv0037JobExitCode;
import org.openapitools.client.model.Dbv0037JobStepCPU;
import org.openapitools.client.model.Dbv0037JobStepNodes;
import org.openapitools.client.model.Dbv0037JobStepStatistics;
import org.openapitools.client.model.Dbv0037JobStepStep;
import org.openapitools.client.model.Dbv0037JobStepTask;
import org.openapitools.client.model.Dbv0037JobStepTasks;
import org.openapitools.client.model.Dbv0037JobStepTime;
import org.openapitools.client.model.Dbv0037JobStepTres;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Dbv0037JobStep
 */
public class Dbv0037JobStepTest {
    private final Dbv0037JobStep model = new Dbv0037JobStep();

    /**
     * Model tests for Dbv0037JobStep
     */
    @Test
    public void testDbv0037JobStep() {
        // TODO: test Dbv0037JobStep
    }

    /**
     * Test the property 'time'
     */
    @Test
    public void timeTest() {
        // TODO: test time
    }

    /**
     * Test the property 'exitCode'
     */
    @Test
    public void exitCodeTest() {
        // TODO: test exitCode
    }

    /**
     * Test the property 'nodes'
     */
    @Test
    public void nodesTest() {
        // TODO: test nodes
    }

    /**
     * Test the property 'tasks'
     */
    @Test
    public void tasksTest() {
        // TODO: test tasks
    }

    /**
     * Test the property 'pid'
     */
    @Test
    public void pidTest() {
        // TODO: test pid
    }

    /**
     * Test the property 'CPU'
     */
    @Test
    public void CPUTest() {
        // TODO: test CPU
    }

    /**
     * Test the property 'killRequestUser'
     */
    @Test
    public void killRequestUserTest() {
        // TODO: test killRequestUser
    }

    /**
     * Test the property 'state'
     */
    @Test
    public void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'statistics'
     */
    @Test
    public void statisticsTest() {
        // TODO: test statistics
    }

    /**
     * Test the property 'step'
     */
    @Test
    public void stepTest() {
        // TODO: test step
    }

    /**
     * Test the property 'task'
     */
    @Test
    public void taskTest() {
        // TODO: test task
    }

    /**
     * Test the property 'tres'
     */
    @Test
    public void tresTest() {
        // TODO: test tres
    }

}
