/*
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Dbv0037JobStepCPURequestedFrequency;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Dbv0037JobStepCPU
 */
public class Dbv0037JobStepCPUTest {
    private final Dbv0037JobStepCPU model = new Dbv0037JobStepCPU();

    /**
     * Model tests for Dbv0037JobStepCPU
     */
    @Test
    public void testDbv0037JobStepCPU() {
        // TODO: test Dbv0037JobStepCPU
    }

    /**
     * Test the property 'requestedFrequency'
     */
    @Test
    public void requestedFrequencyTest() {
        // TODO: test requestedFrequency
    }

    /**
     * Test the property 'governor'
     */
    @Test
    public void governorTest() {
        // TODO: test governor
    }

}
