/*
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Dbv0037QosLimitsMaxWallClockPer
 */
public class Dbv0037QosLimitsMaxWallClockPerTest {
    private final Dbv0037QosLimitsMaxWallClockPer model = new Dbv0037QosLimitsMaxWallClockPer();

    /**
     * Model tests for Dbv0037QosLimitsMaxWallClockPer
     */
    @Test
    public void testDbv0037QosLimitsMaxWallClockPer() {
        // TODO: test Dbv0037QosLimitsMaxWallClockPer
    }

    /**
     * Test the property 'qos'
     */
    @Test
    public void qosTest() {
        // TODO: test qos
    }

    /**
     * Test the property 'job'
     */
    @Test
    public void jobTest() {
        // TODO: test job
    }

}
