/*
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Dbv0037JobTimeTotal
 */
public class Dbv0037JobTimeTotalTest {
    private final Dbv0037JobTimeTotal model = new Dbv0037JobTimeTotal();

    /**
     * Model tests for Dbv0037JobTimeTotal
     */
    @Test
    public void testDbv0037JobTimeTotal() {
        // TODO: test Dbv0037JobTimeTotal
    }

    /**
     * Test the property 'seconds'
     */
    @Test
    public void secondsTest() {
        // TODO: test seconds
    }

    /**
     * Test the property 'microseconds'
     */
    @Test
    public void microsecondsTest() {
        // TODO: test microseconds
    }

}
