/*
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Dbv0037DiagRPCsInner;
import org.openapitools.client.model.Dbv0037DiagRollupsInner;
import org.openapitools.client.model.Dbv0037DiagUsersInner;
import org.openapitools.client.model.Dbv0037Error;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Dbv0037Diag
 */
public class Dbv0037DiagTest {
    private final Dbv0037Diag model = new Dbv0037Diag();

    /**
     * Model tests for Dbv0037Diag
     */
    @Test
    public void testDbv0037Diag() {
        // TODO: test Dbv0037Diag
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

    /**
     * Test the property 'timeStart'
     */
    @Test
    public void timeStartTest() {
        // TODO: test timeStart
    }

    /**
     * Test the property 'rollups'
     */
    @Test
    public void rollupsTest() {
        // TODO: test rollups
    }

    /**
     * Test the property 'rpCs'
     */
    @Test
    public void rpCsTest() {
        // TODO: test rpCs
    }

    /**
     * Test the property 'users'
     */
    @Test
    public void usersTest() {
        // TODO: test users
    }

}
