/*
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Dbv0037TresListInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Dbv0037QosLimitsMaxTresPer
 */
public class Dbv0037QosLimitsMaxTresPerTest {
    private final Dbv0037QosLimitsMaxTresPer model = new Dbv0037QosLimitsMaxTresPer();

    /**
     * Model tests for Dbv0037QosLimitsMaxTresPer
     */
    @Test
    public void testDbv0037QosLimitsMaxTresPer() {
        // TODO: test Dbv0037QosLimitsMaxTresPer
    }

    /**
     * Test the property 'account'
     */
    @Test
    public void accountTest() {
        // TODO: test account
    }

    /**
     * Test the property 'job'
     */
    @Test
    public void jobTest() {
        // TODO: test job
    }

    /**
     * Test the property 'node'
     */
    @Test
    public void nodeTest() {
        // TODO: test node
    }

    /**
     * Test the property 'user'
     */
    @Test
    public void userTest() {
        // TODO: test user
    }

}
