/*
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.Dbv0037AssociationMaxTresMinutesPer;
import org.openapitools.client.model.Dbv0037TresListInner;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Dbv0037AssociationMaxTresMinutes
 */
public class Dbv0037AssociationMaxTresMinutesTest {
    private final Dbv0037AssociationMaxTresMinutes model = new Dbv0037AssociationMaxTresMinutes();

    /**
     * Model tests for Dbv0037AssociationMaxTresMinutes
     */
    @Test
    public void testDbv0037AssociationMaxTresMinutes() {
        // TODO: test Dbv0037AssociationMaxTresMinutes
    }

    /**
     * Test the property 'per'
     */
    @Test
    public void perTest() {
        // TODO: test per
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

}
