/*
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for Dbv0037DiagRPCsInnerTime
 */
public class Dbv0037DiagRPCsInnerTimeTest {
    private final Dbv0037DiagRPCsInnerTime model = new Dbv0037DiagRPCsInnerTime();

    /**
     * Model tests for Dbv0037DiagRPCsInnerTime
     */
    @Test
    public void testDbv0037DiagRPCsInnerTime() {
        // TODO: test Dbv0037DiagRPCsInnerTime
    }

    /**
     * Test the property 'average'
     */
    @Test
    public void averageTest() {
        // TODO: test average
    }

    /**
     * Test the property 'total'
     */
    @Test
    public void totalTest() {
        // TODO: test total
    }

}
