/*
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import org.openapitools.client.model.V0037Error;
import org.openapitools.client.model.V0037Partition;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for V0037PartitionsResponse
 */
public class V0037PartitionsResponseTest {
    private final V0037PartitionsResponse model = new V0037PartitionsResponse();

    /**
     * Model tests for V0037PartitionsResponse
     */
    @Test
    public void testV0037PartitionsResponse() {
        // TODO: test V0037PartitionsResponse
    }

    /**
     * Test the property 'errors'
     */
    @Test
    public void errorsTest() {
        // TODO: test errors
    }

    /**
     * Test the property 'partitions'
     */
    @Test
    public void partitionsTest() {
        // TODO: test partitions
    }

}
