/*
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Dbv0037DiagRPCsInnerTime;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Statistics by RPC type
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Dbv0037DiagRPCsInner {
  public static final String SERIALIZED_NAME_RPC = "rpc";
  @SerializedName(SERIALIZED_NAME_RPC)
  private String rpc;

  public static final String SERIALIZED_NAME_COUNT = "count";
  @SerializedName(SERIALIZED_NAME_COUNT)
  private Integer count;

  public static final String SERIALIZED_NAME_TIME = "time";
  @SerializedName(SERIALIZED_NAME_TIME)
  private Dbv0037DiagRPCsInnerTime time;

  public Dbv0037DiagRPCsInner() {
  }

  public Dbv0037DiagRPCsInner rpc(String rpc) {
    
    this.rpc = rpc;
    return this;
  }

   /**
   * RPC type
   * @return rpc
  **/
  @javax.annotation.Nullable
  public String getRpc() {
    return rpc;
  }


  public void setRpc(String rpc) {
    this.rpc = rpc;
  }


  public Dbv0037DiagRPCsInner count(Integer count) {
    
    this.count = count;
    return this;
  }

   /**
   * Number of RPCs
   * @return count
  **/
  @javax.annotation.Nullable
  public Integer getCount() {
    return count;
  }


  public void setCount(Integer count) {
    this.count = count;
  }


  public Dbv0037DiagRPCsInner time(Dbv0037DiagRPCsInnerTime time) {
    
    this.time = time;
    return this;
  }

   /**
   * Get time
   * @return time
  **/
  @javax.annotation.Nullable
  public Dbv0037DiagRPCsInnerTime getTime() {
    return time;
  }


  public void setTime(Dbv0037DiagRPCsInnerTime time) {
    this.time = time;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Dbv0037DiagRPCsInner dbv0037DiagRPCsInner = (Dbv0037DiagRPCsInner) o;
    return Objects.equals(this.rpc, dbv0037DiagRPCsInner.rpc) &&
        Objects.equals(this.count, dbv0037DiagRPCsInner.count) &&
        Objects.equals(this.time, dbv0037DiagRPCsInner.time);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rpc, count, time);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Dbv0037DiagRPCsInner {\n");
    sb.append("    rpc: ").append(toIndentedString(rpc)).append("\n");
    sb.append("    count: ").append(toIndentedString(count)).append("\n");
    sb.append("    time: ").append(toIndentedString(time)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("rpc");
    openapiFields.add("count");
    openapiFields.add("time");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to Dbv0037DiagRPCsInner
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Dbv0037DiagRPCsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Dbv0037DiagRPCsInner is not found in the empty JSON string", Dbv0037DiagRPCsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Dbv0037DiagRPCsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Dbv0037DiagRPCsInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("rpc") != null && !jsonObj.get("rpc").isJsonNull()) && !jsonObj.get("rpc").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `rpc` to be a primitive type in the JSON string but got `%s`", jsonObj.get("rpc").toString()));
      }
      // validate the optional field `time`
      if (jsonObj.get("time") != null && !jsonObj.get("time").isJsonNull()) {
        Dbv0037DiagRPCsInnerTime.validateJsonElement(jsonObj.get("time"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Dbv0037DiagRPCsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Dbv0037DiagRPCsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Dbv0037DiagRPCsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Dbv0037DiagRPCsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<Dbv0037DiagRPCsInner>() {
           @Override
           public void write(JsonWriter out, Dbv0037DiagRPCsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Dbv0037DiagRPCsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Dbv0037DiagRPCsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Dbv0037DiagRPCsInner
  * @throws IOException if the JSON string is invalid with respect to Dbv0037DiagRPCsInner
  */
  public static Dbv0037DiagRPCsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Dbv0037DiagRPCsInner.class);
  }

 /**
  * Convert an instance of Dbv0037DiagRPCsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

