/*
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;
import org.openapitools.client.model.Dbv0037JobStepStatisticsCPU;
import org.openapitools.client.model.Dbv0037JobStepStatisticsEnergy;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Statistics of job step
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Dbv0037JobStepStatistics {
  public static final String SERIALIZED_NAME_C_P_U = "CPU";
  @SerializedName(SERIALIZED_NAME_C_P_U)
  private Dbv0037JobStepStatisticsCPU CPU;

  public static final String SERIALIZED_NAME_ENERGY = "energy";
  @SerializedName(SERIALIZED_NAME_ENERGY)
  private Dbv0037JobStepStatisticsEnergy energy;

  public Dbv0037JobStepStatistics() {
  }

  public Dbv0037JobStepStatistics CPU(Dbv0037JobStepStatisticsCPU CPU) {
    
    this.CPU = CPU;
    return this;
  }

   /**
   * Get CPU
   * @return CPU
  **/
  @javax.annotation.Nullable
  public Dbv0037JobStepStatisticsCPU getCPU() {
    return CPU;
  }


  public void setCPU(Dbv0037JobStepStatisticsCPU CPU) {
    this.CPU = CPU;
  }


  public Dbv0037JobStepStatistics energy(Dbv0037JobStepStatisticsEnergy energy) {
    
    this.energy = energy;
    return this;
  }

   /**
   * Get energy
   * @return energy
  **/
  @javax.annotation.Nullable
  public Dbv0037JobStepStatisticsEnergy getEnergy() {
    return energy;
  }


  public void setEnergy(Dbv0037JobStepStatisticsEnergy energy) {
    this.energy = energy;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Dbv0037JobStepStatistics dbv0037JobStepStatistics = (Dbv0037JobStepStatistics) o;
    return Objects.equals(this.CPU, dbv0037JobStepStatistics.CPU) &&
        Objects.equals(this.energy, dbv0037JobStepStatistics.energy);
  }

  @Override
  public int hashCode() {
    return Objects.hash(CPU, energy);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Dbv0037JobStepStatistics {\n");
    sb.append("    CPU: ").append(toIndentedString(CPU)).append("\n");
    sb.append("    energy: ").append(toIndentedString(energy)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("CPU");
    openapiFields.add("energy");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to Dbv0037JobStepStatistics
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Dbv0037JobStepStatistics.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Dbv0037JobStepStatistics is not found in the empty JSON string", Dbv0037JobStepStatistics.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Dbv0037JobStepStatistics.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Dbv0037JobStepStatistics` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      // validate the optional field `CPU`
      if (jsonObj.get("CPU") != null && !jsonObj.get("CPU").isJsonNull()) {
        Dbv0037JobStepStatisticsCPU.validateJsonElement(jsonObj.get("CPU"));
      }
      // validate the optional field `energy`
      if (jsonObj.get("energy") != null && !jsonObj.get("energy").isJsonNull()) {
        Dbv0037JobStepStatisticsEnergy.validateJsonElement(jsonObj.get("energy"));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Dbv0037JobStepStatistics.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Dbv0037JobStepStatistics' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Dbv0037JobStepStatistics> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Dbv0037JobStepStatistics.class));

       return (TypeAdapter<T>) new TypeAdapter<Dbv0037JobStepStatistics>() {
           @Override
           public void write(JsonWriter out, Dbv0037JobStepStatistics value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Dbv0037JobStepStatistics read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Dbv0037JobStepStatistics given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Dbv0037JobStepStatistics
  * @throws IOException if the JSON string is invalid with respect to Dbv0037JobStepStatistics
  */
  public static Dbv0037JobStepStatistics fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Dbv0037JobStepStatistics.class);
  }

 /**
  * Convert an instance of Dbv0037JobStepStatistics to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

