/*
 * Slurm Rest API
 * API to access and control Slurm.
 *
 * The version of the OpenAPI document: 0.0.37
 * Contact: sales@schedmd.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;
import java.util.Arrays;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonArray;
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonObject;
import com.google.gson.JsonParseException;
import com.google.gson.TypeAdapterFactory;
import com.google.gson.reflect.TypeToken;
import com.google.gson.TypeAdapter;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import java.io.IOException;

import java.lang.reflect.Type;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;
import java.util.Set;

import org.openapitools.client.JSON;

/**
 * Rollup statistics
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen")
public class Dbv0037DiagRollupsInner {
  public static final String SERIALIZED_NAME_TYPE = "type";
  @SerializedName(SERIALIZED_NAME_TYPE)
  private String type;

  public static final String SERIALIZED_NAME_LAST_RUN = "last_run";
  @SerializedName(SERIALIZED_NAME_LAST_RUN)
  private Integer lastRun;

  public static final String SERIALIZED_NAME_LAST_CYCLE = "last_cycle";
  @SerializedName(SERIALIZED_NAME_LAST_CYCLE)
  private Integer lastCycle;

  public static final String SERIALIZED_NAME_MAX_CYCLE = "max_cycle";
  @SerializedName(SERIALIZED_NAME_MAX_CYCLE)
  private Integer maxCycle;

  public static final String SERIALIZED_NAME_TOTAL_TIME = "total_time";
  @SerializedName(SERIALIZED_NAME_TOTAL_TIME)
  private Integer totalTime;

  public static final String SERIALIZED_NAME_MEAN_CYCLES = "mean_cycles";
  @SerializedName(SERIALIZED_NAME_MEAN_CYCLES)
  private Integer meanCycles;

  public Dbv0037DiagRollupsInner() {
  }

  public Dbv0037DiagRollupsInner type(String type) {
    
    this.type = type;
    return this;
  }

   /**
   * Type of rollup
   * @return type
  **/
  @javax.annotation.Nullable
  public String getType() {
    return type;
  }


  public void setType(String type) {
    this.type = type;
  }


  public Dbv0037DiagRollupsInner lastRun(Integer lastRun) {
    
    this.lastRun = lastRun;
    return this;
  }

   /**
   * Timestamp of last rollup
   * @return lastRun
  **/
  @javax.annotation.Nullable
  public Integer getLastRun() {
    return lastRun;
  }


  public void setLastRun(Integer lastRun) {
    this.lastRun = lastRun;
  }


  public Dbv0037DiagRollupsInner lastCycle(Integer lastCycle) {
    
    this.lastCycle = lastCycle;
    return this;
  }

   /**
   * Timestamp of last cycle
   * @return lastCycle
  **/
  @javax.annotation.Nullable
  public Integer getLastCycle() {
    return lastCycle;
  }


  public void setLastCycle(Integer lastCycle) {
    this.lastCycle = lastCycle;
  }


  public Dbv0037DiagRollupsInner maxCycle(Integer maxCycle) {
    
    this.maxCycle = maxCycle;
    return this;
  }

   /**
   * Max time of all cycles
   * @return maxCycle
  **/
  @javax.annotation.Nullable
  public Integer getMaxCycle() {
    return maxCycle;
  }


  public void setMaxCycle(Integer maxCycle) {
    this.maxCycle = maxCycle;
  }


  public Dbv0037DiagRollupsInner totalTime(Integer totalTime) {
    
    this.totalTime = totalTime;
    return this;
  }

   /**
   * Total time (s) spent doing rollup
   * @return totalTime
  **/
  @javax.annotation.Nullable
  public Integer getTotalTime() {
    return totalTime;
  }


  public void setTotalTime(Integer totalTime) {
    this.totalTime = totalTime;
  }


  public Dbv0037DiagRollupsInner meanCycles(Integer meanCycles) {
    
    this.meanCycles = meanCycles;
    return this;
  }

   /**
   * Average time (s) of cycle
   * @return meanCycles
  **/
  @javax.annotation.Nullable
  public Integer getMeanCycles() {
    return meanCycles;
  }


  public void setMeanCycles(Integer meanCycles) {
    this.meanCycles = meanCycles;
  }



  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Dbv0037DiagRollupsInner dbv0037DiagRollupsInner = (Dbv0037DiagRollupsInner) o;
    return Objects.equals(this.type, dbv0037DiagRollupsInner.type) &&
        Objects.equals(this.lastRun, dbv0037DiagRollupsInner.lastRun) &&
        Objects.equals(this.lastCycle, dbv0037DiagRollupsInner.lastCycle) &&
        Objects.equals(this.maxCycle, dbv0037DiagRollupsInner.maxCycle) &&
        Objects.equals(this.totalTime, dbv0037DiagRollupsInner.totalTime) &&
        Objects.equals(this.meanCycles, dbv0037DiagRollupsInner.meanCycles);
  }

  @Override
  public int hashCode() {
    return Objects.hash(type, lastRun, lastCycle, maxCycle, totalTime, meanCycles);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Dbv0037DiagRollupsInner {\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    lastRun: ").append(toIndentedString(lastRun)).append("\n");
    sb.append("    lastCycle: ").append(toIndentedString(lastCycle)).append("\n");
    sb.append("    maxCycle: ").append(toIndentedString(maxCycle)).append("\n");
    sb.append("    totalTime: ").append(toIndentedString(totalTime)).append("\n");
    sb.append("    meanCycles: ").append(toIndentedString(meanCycles)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }


  public static HashSet<String> openapiFields;
  public static HashSet<String> openapiRequiredFields;

  static {
    // a set of all properties/fields (JSON key names)
    openapiFields = new HashSet<String>();
    openapiFields.add("type");
    openapiFields.add("last_run");
    openapiFields.add("last_cycle");
    openapiFields.add("max_cycle");
    openapiFields.add("total_time");
    openapiFields.add("mean_cycles");

    // a set of required properties/fields (JSON key names)
    openapiRequiredFields = new HashSet<String>();
  }

 /**
  * Validates the JSON Element and throws an exception if issues found
  *
  * @param jsonElement JSON Element
  * @throws IOException if the JSON Element is invalid with respect to Dbv0037DiagRollupsInner
  */
  public static void validateJsonElement(JsonElement jsonElement) throws IOException {
      if (jsonElement == null) {
        if (!Dbv0037DiagRollupsInner.openapiRequiredFields.isEmpty()) { // has required fields but JSON element is null
          throw new IllegalArgumentException(String.format("The required field(s) %s in Dbv0037DiagRollupsInner is not found in the empty JSON string", Dbv0037DiagRollupsInner.openapiRequiredFields.toString()));
        }
      }

      Set<Map.Entry<String, JsonElement>> entries = jsonElement.getAsJsonObject().entrySet();
      // check to see if the JSON string contains additional fields
      for (Map.Entry<String, JsonElement> entry : entries) {
        if (!Dbv0037DiagRollupsInner.openapiFields.contains(entry.getKey())) {
          throw new IllegalArgumentException(String.format("The field `%s` in the JSON string is not defined in the `Dbv0037DiagRollupsInner` properties. JSON: %s", entry.getKey(), jsonElement.toString()));
        }
      }
        JsonObject jsonObj = jsonElement.getAsJsonObject();
      if ((jsonObj.get("type") != null && !jsonObj.get("type").isJsonNull()) && !jsonObj.get("type").isJsonPrimitive()) {
        throw new IllegalArgumentException(String.format("Expected the field `type` to be a primitive type in the JSON string but got `%s`", jsonObj.get("type").toString()));
      }
  }

  public static class CustomTypeAdapterFactory implements TypeAdapterFactory {
    @SuppressWarnings("unchecked")
    @Override
    public <T> TypeAdapter<T> create(Gson gson, TypeToken<T> type) {
       if (!Dbv0037DiagRollupsInner.class.isAssignableFrom(type.getRawType())) {
         return null; // this class only serializes 'Dbv0037DiagRollupsInner' and its subtypes
       }
       final TypeAdapter<JsonElement> elementAdapter = gson.getAdapter(JsonElement.class);
       final TypeAdapter<Dbv0037DiagRollupsInner> thisAdapter
                        = gson.getDelegateAdapter(this, TypeToken.get(Dbv0037DiagRollupsInner.class));

       return (TypeAdapter<T>) new TypeAdapter<Dbv0037DiagRollupsInner>() {
           @Override
           public void write(JsonWriter out, Dbv0037DiagRollupsInner value) throws IOException {
             JsonObject obj = thisAdapter.toJsonTree(value).getAsJsonObject();
             elementAdapter.write(out, obj);
           }

           @Override
           public Dbv0037DiagRollupsInner read(JsonReader in) throws IOException {
             JsonElement jsonElement = elementAdapter.read(in);
             validateJsonElement(jsonElement);
             return thisAdapter.fromJsonTree(jsonElement);
           }

       }.nullSafe();
    }
  }

 /**
  * Create an instance of Dbv0037DiagRollupsInner given an JSON string
  *
  * @param jsonString JSON string
  * @return An instance of Dbv0037DiagRollupsInner
  * @throws IOException if the JSON string is invalid with respect to Dbv0037DiagRollupsInner
  */
  public static Dbv0037DiagRollupsInner fromJson(String jsonString) throws IOException {
    return JSON.getGson().fromJson(jsonString, Dbv0037DiagRollupsInner.class);
  }

 /**
  * Convert an instance of Dbv0037DiagRollupsInner to an JSON string
  *
  * @return JSON string
  */
  public String toJson() {
    return JSON.getGson().toJson(this);
  }
}

