# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, conlist
from openapi_client.models.dbv0037_tres_list_inner import Dbv0037TresListInner

class Dbv0037JobStepTresRequested(BaseModel):
    """
    TRES requested for job  # noqa: E501
    """
    average: Optional[conlist(Dbv0037TresListInner)] = Field(None, description="TRES list of attributes")
    max: Optional[conlist(Dbv0037TresListInner)] = Field(None, description="TRES list of attributes")
    min: Optional[conlist(Dbv0037TresListInner)] = Field(None, description="TRES list of attributes")
    total: Optional[conlist(Dbv0037TresListInner)] = Field(None, description="TRES list of attributes")
    __properties = ["average", "max", "min", "total"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Dbv0037JobStepTresRequested:
        """Create an instance of Dbv0037JobStepTresRequested from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in average (list)
        _items = []
        if self.average:
            for _item in self.average:
                if _item:
                    _items.append(_item.to_dict())
            _dict['average'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in max (list)
        _items = []
        if self.max:
            for _item in self.max:
                if _item:
                    _items.append(_item.to_dict())
            _dict['max'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in min (list)
        _items = []
        if self.min:
            for _item in self.min:
                if _item:
                    _items.append(_item.to_dict())
            _dict['min'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in total (list)
        _items = []
        if self.total:
            for _item in self.total:
                if _item:
                    _items.append(_item.to_dict())
            _dict['total'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Dbv0037JobStepTresRequested:
        """Create an instance of Dbv0037JobStepTresRequested from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Dbv0037JobStepTresRequested.parse_obj(obj)

        _obj = Dbv0037JobStepTresRequested.parse_obj({
            "average": [Dbv0037TresListInner.from_dict(_item) for _item in obj.get("average")] if obj.get("average") is not None else None,
            "max": [Dbv0037TresListInner.from_dict(_item) for _item in obj.get("max")] if obj.get("max") is not None else None,
            "min": [Dbv0037TresListInner.from_dict(_item) for _item in obj.get("min")] if obj.get("min") is not None else None,
            "total": [Dbv0037TresListInner.from_dict(_item) for _item in obj.get("total")] if obj.get("total") is not None else None
        })
        return _obj


