# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr

class Dbv0037TresListInner(BaseModel):
    """
    Dbv0037TresListInner
    """
    type: Optional[StrictStr] = Field(None, description="TRES type")
    name: Optional[StrictStr] = Field(None, description="TRES name (optional)")
    id: Optional[StrictInt] = Field(None, description="database id")
    count: Optional[StrictInt] = Field(None, description="count of TRES")
    __properties = ["type", "name", "id", "count"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Dbv0037TresListInner:
        """Create an instance of Dbv0037TresListInner from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> Dbv0037TresListInner:
        """Create an instance of Dbv0037TresListInner from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return Dbv0037TresListInner.parse_obj(obj)

        _obj = Dbv0037TresListInner.parse_obj({
            "type": obj.get("type"),
            "name": obj.get("name"),
            "id": obj.get("id"),
            "count": obj.get("count")
        })
        return _obj


