# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr, conlist
from openapi_client.models.v0037_node_allocation import V0037NodeAllocation

class V0037JobResources(BaseModel):
    """
    V0037JobResources
    """
    nodes: Optional[StrictStr] = Field(None, description="list of assigned job nodes")
    allocated_cpus: Optional[StrictInt] = Field(None, description="number of assigned job cpus")
    allocated_hosts: Optional[StrictInt] = Field(None, description="number of assigned job hosts")
    allocated_nodes: Optional[conlist(V0037NodeAllocation)] = Field(None, description="node allocations")
    __properties = ["nodes", "allocated_cpus", "allocated_hosts", "allocated_nodes"]

    class Config:
        """Pydantic configuration"""
        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> V0037JobResources:
        """Create an instance of V0037JobResources from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True,
                          exclude={
                          },
                          exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in allocated_nodes (list)
        _items = []
        if self.allocated_nodes:
            for _item in self.allocated_nodes:
                if _item:
                    _items.append(_item.to_dict())
            _dict['allocated_nodes'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> V0037JobResources:
        """Create an instance of V0037JobResources from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return V0037JobResources.parse_obj(obj)

        _obj = V0037JobResources.parse_obj({
            "nodes": obj.get("nodes"),
            "allocated_cpus": obj.get("allocated_cpus"),
            "allocated_hosts": obj.get("allocated_hosts"),
            "allocated_nodes": [V0037NodeAllocation.from_dict(_item) for _item in obj.get("allocated_nodes")] if obj.get("allocated_nodes") is not None else None
        })
        return _obj


