# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dbv0037_config_info import Dbv0037ConfigInfo  # noqa: E501

class TestDbv0037ConfigInfo(unittest.TestCase):
    """Dbv0037ConfigInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dbv0037ConfigInfo:
        """Test Dbv0037ConfigInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dbv0037ConfigInfo`
        """
        model = Dbv0037ConfigInfo()  # noqa: E501
        if include_optional:
            return Dbv0037ConfigInfo(
                errors = [
                    openapi_client.models.dbv0/0/37_error.dbv0.0.37_error(
                        errno = 56, 
                        error = '', )
                    ],
                tres = [
                    [
                        openapi_client.models.dbv0_0_37_tres_list_inner.dbv0_0_37_tres_list_inner(
                            type = '', 
                            name = '', 
                            id = 56, 
                            count = 56, )
                        ]
                    ],
                accounts = [
                    openapi_client.models.dbv0/0/37_account.dbv0.0.37_account(
                        associations = [
                            openapi_client.models.dbv0/0/37_association_short_info.dbv0.0.37_association_short_info(
                                account = '', 
                                cluster = '', 
                                partition = '', 
                                user = '', )
                            ], 
                        coordinators = [
                            openapi_client.models.dbv0/0/37_coordinator_info.dbv0.0.37_coordinator_info(
                                name = '', 
                                direct = 56, )
                            ], 
                        description = '', 
                        name = '', 
                        organization = '', 
                        flags = [
                            ''
                            ], )
                    ],
                associations = [
                    openapi_client.models.dbv0/0/37_association.dbv0.0.37_association(
                        is_default = 56, 
                        account = '', 
                        cluster = '', 
                        default = openapi_client.models.dbv0_0_37_association_default.dbv0_0_37_association_default(
                            qos = '', ), 
                        flags = [
                            ''
                            ], 
                        max = openapi_client.models.dbv0_0_37_association_max.dbv0_0_37_association_max(
                            jobs = openapi_client.models.dbv0_0_37_association_max_jobs.dbv0_0_37_association_max_jobs(
                                active = 56, 
                                accruing = 56, 
                                total = 56, 
                                per = openapi_client.models.dbv0_0_37_association_max_jobs_per.dbv0_0_37_association_max_jobs_per(
                                    wall_clock = 56, ), ), 
                            per = openapi_client.models.dbv0_0_37_association_max_per.dbv0_0_37_association_max_per(
                                account = openapi_client.models.dbv0_0_37_association_max_per_account.dbv0_0_37_association_max_per_account(
                                    wall_clock = 56, ), ), 
                            tres = openapi_client.models.dbv0_0_37_association_max_tres.dbv0_0_37_association_max_tres(
                                group = openapi_client.models.dbv0_0_37_association_max_tres_group.dbv0_0_37_association_max_tres_group(
                                    minutes = [
                                        openapi_client.models.dbv0_0_37_tres_list_inner.dbv0_0_37_tres_list_inner(
                                            type = '', 
                                            name = '', 
                                            id = 56, 
                                            count = 56, )
                                        ], 
                                    active = [
                                        openapi_client.models.dbv0_0_37_tres_list_inner.dbv0_0_37_tres_list_inner(
                                            type = '', 
                                            name = '', 
                                            id = 56, 
                                            count = 56, )
                                        ], ), 
                                total = , 
                                minutes = openapi_client.models.dbv0_0_37_association_max_tres_minutes.dbv0_0_37_association_max_tres_minutes(), ), ), 
                        min = openapi_client.models.dbv0_0_37_association_min.dbv0_0_37_association_min(
                            priority_threshold = 56, ), 
                        parent_account = '', 
                        partition = '', 
                        priority = 56, 
                        qos = [
                            ''
                            ], 
                        shares_raw = 56, 
                        usage = openapi_client.models.dbv0_0_37_association_usage.dbv0_0_37_association_usage(
                            accrue_job_count = 56, 
                            group_used_wallclock = 1.337, 
                            fairshare_factor = 1.337, 
                            fairshare_shares = 56, 
                            normalized_priority = 56, 
                            normalized_shares = 1.337, 
                            effective_normalized_usage = 1.337, 
                            raw_usage = 56, 
                            job_count = 56, 
                            fairshare_level = 1.337, ), 
                        user = '', )
                    ],
                users = [
                    openapi_client.models.dbv0/0/37_user.dbv0.0.37_user(
                        administrator_level = '', 
                        associations = openapi_client.models.dbv0_0_37_user_associations.dbv0_0_37_user_associations(
                            root = openapi_client.models.dbv0/0/37_association_short_info.dbv0.0.37_association_short_info(
                                account = '', 
                                cluster = '', 
                                partition = '', 
                                user = '', ), ), 
                        coordinators = [
                            openapi_client.models.dbv0/0/37_coordinator_info.dbv0.0.37_coordinator_info(
                                name = '', 
                                direct = 56, )
                            ], 
                        default = openapi_client.models.dbv0_0_37_user_default.dbv0_0_37_user_default(
                            account = '', 
                            wckey = '', ), 
                        name = '', )
                    ],
                qos = [
                    openapi_client.models.dbv0/0/37_qos.dbv0.0.37_qos(
                        description = '', 
                        flags = [
                            ''
                            ], 
                        id = '', 
                        limits = openapi_client.models.dbv0_0_37_qos_limits.dbv0_0_37_qos_limits(
                            factor = 1.337, 
                            max = openapi_client.models.dbv0_0_37_qos_limits_max.dbv0_0_37_qos_limits_max(
                                wall_clock = openapi_client.models.dbv0_0_37_qos_limits_max_wall_clock.dbv0_0_37_qos_limits_max_wall_clock(
                                    per = openapi_client.models.dbv0_0_37_qos_limits_max_wall_clock_per.dbv0_0_37_qos_limits_max_wall_clock_per(
                                        qos = 56, 
                                        job = 56, ), ), 
                                jobs = openapi_client.models.dbv0_0_37_qos_limits_max_jobs.dbv0_0_37_qos_limits_max_jobs(
                                    active_jobs = openapi_client.models.dbv0_0_37_qos_limits_max_jobs_active_jobs.dbv0_0_37_qos_limits_max_jobs_active_jobs(), ), 
                                accruing = openapi_client.models.dbv0_0_37_qos_limits_max_accruing.dbv0_0_37_qos_limits_max_accruing(), 
                                tres = openapi_client.models.dbv0_0_37_qos_limits_max_tres.dbv0_0_37_qos_limits_max_tres(
                                    minutes = openapi_client.models.dbv0_0_37_qos_limits_max_tres_minutes.dbv0_0_37_qos_limits_max_tres_minutes(), ), ), 
                            min = openapi_client.models.dbv0_0_37_qos_limits_min.dbv0_0_37_qos_limits_min(
                                priority_threshold = 56, ), ), 
                        preempt = openapi_client.models.dbv0_0_37_qos_preempt.dbv0_0_37_qos_preempt(
                            list = [
                                ''
                                ], 
                            mode = [
                                ''
                                ], 
                            exempt_time = 56, ), 
                        priority = 56, 
                        usage_factor = 1.337, 
                        usage_threshold = 1.337, )
                    ],
                wckeys = [
                    openapi_client.models.dbv0/0/37_wckey.dbv0.0.37_wckey(
                        accounts = [
                            ''
                            ], 
                        cluster = '', 
                        id = 56, 
                        name = '', 
                        user = '', 
                        flags = [
                            ''
                            ], )
                    ]
            )
        else:
            return Dbv0037ConfigInfo(
        )
        """

    def testDbv0037ConfigInfo(self):
        """Test Dbv0037ConfigInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
