# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.dbv0037_job_info import Dbv0037JobInfo  # noqa: E501

class TestDbv0037JobInfo(unittest.TestCase):
    """Dbv0037JobInfo unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Dbv0037JobInfo:
        """Test Dbv0037JobInfo
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Dbv0037JobInfo`
        """
        model = Dbv0037JobInfo()  # noqa: E501
        if include_optional:
            return Dbv0037JobInfo(
                errors = [
                    openapi_client.models.dbv0/0/37_error.dbv0.0.37_error(
                        errno = 56, 
                        error = '', )
                    ],
                jobs = [
                    openapi_client.models.dbv0/0/37_job.dbv0.0.37_job(
                        account = '', 
                        comment = openapi_client.models.dbv0_0_37_job_comment.dbv0_0_37_job_comment(
                            administrator = '', 
                            job = '', 
                            system = '', ), 
                        allocation_nodes = '', 
                        array = openapi_client.models.dbv0_0_37_job_array.dbv0_0_37_job_array(
                            job_id = 56, 
                            limits = openapi_client.models.dbv0_0_37_job_array_limits.dbv0_0_37_job_array_limits(
                                max = openapi_client.models.dbv0_0_37_job_array_limits_max.dbv0_0_37_job_array_limits_max(
                                    running = openapi_client.models.dbv0_0_37_job_array_limits_max_running.dbv0_0_37_job_array_limits_max_running(
                                        tasks = 56, ), ), ), 
                            task = '', 
                            task_id = 56, ), 
                        time = openapi_client.models.dbv0_0_37_job_time.dbv0_0_37_job_time(
                            elapsed = 56, 
                            eligible = 56, 
                            end = 56, 
                            start = 56, 
                            submission = 56, 
                            suspended = 56, 
                            system = openapi_client.models.dbv0_0_37_job_time_system.dbv0_0_37_job_time_system(
                                seconds = 56, 
                                microseconds = 56, ), 
                            total = openapi_client.models.dbv0_0_37_job_time_total.dbv0_0_37_job_time_total(
                                seconds = 56, 
                                microseconds = 56, ), 
                            user = openapi_client.models.dbv0_0_37_job_time_user.dbv0_0_37_job_time_user(
                                seconds = 56, 
                                microseconds = 56, ), 
                            limit = 56, ), 
                        association = openapi_client.models.dbv0/0/37_association_short_info.dbv0.0.37_association_short_info(
                            account = '', 
                            cluster = '', 
                            partition = '', ), 
                        cluster = '', 
                        constraints = '', 
                        derived_exit_code = openapi_client.models.dbv0/0/37_job_exit_code.dbv0.0.37_job_exit_code(
                            status = '', 
                            return_code = 56, 
                            signal = openapi_client.models.dbv0_0_37_job_exit_code_signal.dbv0_0_37_job_exit_code_signal(
                                signal_id = 56, 
                                name = '', ), ), 
                        exit_code = openapi_client.models.dbv0/0/37_job_exit_code.dbv0.0.37_job_exit_code(
                            status = '', 
                            return_code = 56, ), 
                        flags = [
                            ''
                            ], 
                        group = '', 
                        het = openapi_client.models.dbv0_0_37_job_het.dbv0_0_37_job_het(
                            job_id = openapi_client.models.job_id.job_id(), 
                            job_offset = openapi_client.models.job_offset.job_offset(), ), 
                        job_id = 56, 
                        name = '', 
                        mcs = openapi_client.models.dbv0_0_37_job_mcs.dbv0_0_37_job_mcs(
                            label = '', ), 
                        nodes = '', 
                        partition = '', 
                        priority = 56, 
                        qos = '', 
                        required = openapi_client.models.dbv0_0_37_job_required.dbv0_0_37_job_required(
                            cpus = 56, 
                            memory = 56, ), 
                        kill_request_user = '', 
                        reservation = openapi_client.models.dbv0_0_37_job_reservation.dbv0_0_37_job_reservation(
                            id = 56, 
                            name = 56, ), 
                        state = openapi_client.models.dbv0_0_37_job_state.dbv0_0_37_job_state(
                            current = '', 
                            reason = '', ), 
                        steps = [
                            openapi_client.models.dbv0/0/37_job_step.dbv0.0.37_job_step(
                                nodes = openapi_client.models.dbv0_0_37_job_step_nodes.dbv0_0_37_job_step_nodes(
                                    count = 56, 
                                    range = '', ), 
                                tasks = openapi_client.models.dbv0_0_37_job_step_tasks.dbv0_0_37_job_step_tasks(
                                    count = 56, ), 
                                pid = '', 
                                cpu = openapi_client.models.dbv0_0_37_job_step_cpu.dbv0_0_37_job_step_CPU(
                                    requested_frequency = openapi_client.models.dbv0_0_37_job_step_cpu_requested_frequency.dbv0_0_37_job_step_CPU_requested_frequency(
                                        min = 56, ), 
                                    governor = [
                                        ''
                                        ], ), 
                                kill_request_user = '', 
                                statistics = openapi_client.models.dbv0_0_37_job_step_statistics.dbv0_0_37_job_step_statistics(
                                    energy = openapi_client.models.dbv0_0_37_job_step_statistics_energy.dbv0_0_37_job_step_statistics_energy(
                                        consumed = 56, ), ), 
                                step = openapi_client.models.dbv0_0_37_job_step_step.dbv0_0_37_job_step_step(
                                    job_id = 56, 
                                    id = '', 
                                    name = '', ), 
                                task = openapi_client.models.dbv0_0_37_job_step_task.dbv0_0_37_job_step_task(
                                    distribution = '', ), 
                                tres = openapi_client.models.dbv0_0_37_job_step_tres.dbv0_0_37_job_step_tres(
                                    requested = openapi_client.models.dbv0_0_37_job_step_tres_requested.dbv0_0_37_job_step_tres_requested(
                                        average = [
                                            openapi_client.models.dbv0_0_37_tres_list_inner.dbv0_0_37_tres_list_inner(
                                                type = '', 
                                                name = '', 
                                                id = 56, 
                                                count = 56, )
                                            ], 
                                        min = [
                                            openapi_client.models.dbv0_0_37_tres_list_inner.dbv0_0_37_tres_list_inner(
                                                type = '', 
                                                name = '', 
                                                id = 56, 
                                                count = 56, )
                                            ], ), 
                                    consumed = openapi_client.models.dbv0_0_37_job_step_tres_requested.dbv0_0_37_job_step_tres_requested(), 
                                    allocated = , ), )
                            ], 
                        tres = openapi_client.models.dbv0_0_37_job_tres.dbv0_0_37_job_tres(), 
                        user = '', 
                        wckey = openapi_client.models.dbv0_0_37_job_wckey.dbv0_0_37_job_wckey(), 
                        working_directory = '', )
                    ]
            )
        else:
            return Dbv0037JobInfo(
        )
        """

    def testDbv0037JobInfo(self):
        """Test Dbv0037JobInfo"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
