# coding: utf-8

"""
    Slurm Rest API

    API to access and control Slurm.

    The version of the OpenAPI document: 0.0.37
    Contact: sales@schedmd.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.default_api import DefaultApi  # noqa: E501


class TestDefaultApi(unittest.TestCase):
    """DefaultApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DefaultApi()  # noqa: E501

    def tearDown(self) -> None:
        pass

    def test_openapi_get(self) -> None:
        """Test case for openapi_get

        Retrieve OpenAPI Specification  # noqa: E501
        """
        pass

    def test_openapi_json_get(self) -> None:
        """Test case for openapi_json_get

        Retrieve OpenAPI Specification  # noqa: E501
        """
        pass

    def test_openapi_v3_get(self) -> None:
        """Test case for openapi_v3_get

        Retrieve OpenAPI Specification  # noqa: E501
        """
        pass

    def test_openapi_yaml_get(self) -> None:
        """Test case for openapi_yaml_get

        Retrieve OpenAPI Specification  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
